class Exporter
  def self.process(report, search)
    report_builder=BatchBuilder.new(report, search)

    xlsx_package = Axlsx::Package.new
    wb = xlsx_package.workbook

    styles = wb.styles
    title = styles.add_style(:sz => 15, :b => true, :u => true, :alignment => {:horizontal => :center})
    default = styles.add_style(:border => Axlsx::STYLE_THIN_BORDER)
    header = styles.add_style(:bg_color => '00', :fg_color => 'FF', :b => true, :alignment => {:horizontal => :center})
    tbl_header = styles.add_style :b => true, :alignment => {:horizontal => :center}, :border => Axlsx::STYLE_THIN_BORDER
    ind_header = styles.add_style :bg_color => "FFDFDEDF", :b => true, :alignment => {:indent => 1}
    col_header = styles.add_style :bg_color => "FFDFDEDF", :b => true, :alignment => {:horizontal => :center}
    data_fmt = styles.add_style :alignment => {:indent => 1}
    standard = styles.add_style :b => true, :alignment => {:horizontal => :center}

    wb.add_worksheet(name: report.main_type) do |sheet|
      sheet.add_row report_builder.columns, :style => header
      report_builder.each_data do |data|
        data.each do |row|
          puts row.inspect
          sheet.add_row row, :style => data_fmt
          sheet.column_widths 16, 16, 16, 16, 16, 16, 16, 16, 16
        end
      end
      wb.add_worksheet(name: 'infos') do |sheet|
          sheet.add_row ['generated by', 'omni inventory v0.1'] , :style => [header, standard]
          sheet.add_row ['generation date', Time.new.strftime("%Y-%m-%d %H:%M:%S")], :style => [header, standard]
          sheet.add_row
      end
    end
    xlsx_package.serialize('simple.xlsx')
  end

end
